### ISSUE TITLE
Add instructions for getting permission to add secrets

### ISSUE THREAD

**Issue by klahnakoski** [armenzg/smart-scheduling#10]
I am able to view the example secret.  I can not add new ones.

![image](https://user-images.githubusercontent.com/2334429/78888343-700a5b80-7a2f-11ea-9b42-6b0efa2c2651.png)

**Comment by armenzg** [comment]
Do you have this issue if you prepend "project/cia" to the path of the secret?

**Comment by klahnakoski** [comment]
fixed: you and I have both sequenced this
