### ISSUE TITLE
Manage our own hooks

### ISSUE THREAD

**Issue by armenzg** [armenzg/smart-scheduling#2]
Currently I define it by hand in ([example](https://community-tc.services.mozilla.com/hooks/project-cia/hello-world)).

**Comment by marco-c** [comment]
I'd suggest using [task-boot](https://github.com/mozilla/task-boot) for this, docs available at https://github.com/mozilla/task-boot/wiki/BuildHook. @La0 and me can help you if needed.

**Comment by armenzg** [comment]
Moved https://github.com/mozilla/cia-tasks/issues/5
